server:
  port: 8081
spring:
  profiles:
    active: db
 #Resolve the conflict issue between SpringBoot2.6.0 and Swagger [The reason is that the default path matching policy for SpringMVC was changed from AntPathMatcher to PathPatternParser in SpringBoot2.6.0, which caused an error. The solution is to switch back to the original AntPathMatcher]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    #Template mode, supporting HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #Encoding does not require configuration
    encoding: UTF-8
    #The development configuration is set to false, avoiding template modifications and restarting the server
    cache: false
    #Configure the template path. The default is templates, and configuration is not required
    prefix: classpath:/static/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    #Set file upload limit
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    #Add log support
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml